#
# FileName:     Makefile
# Author: 		8ucchiman
# CreatedDate:  2023-12-15 19:58:31
# LastModified: 2023-12-15 20:09:10
# Reference: 	https://qiita.com/chibi929/items/b8c5f36434d5d3fbfa4a
# Description:	---
#




